### ISSUE TITLE
Building errors with libboost1.55

### ISSUE THREAD

**Issue by kocio-pl** [xingfuryda/openstreetmap-tiles-docker#1]
I was looking why this image doesn't build and found that you should not try to install particular boost version (1.55):

`RUN apt-get install -y make cmake libboost1.55-dev libboost-filesystem1.55-dev libboost-program-options1.55-dev libboost-python1.55-dev libboost-regex1.55-dev libboost-system1.55-dev libboost-thread1.55-dev`

because libmapnik-dev has more general dependencies, and instead use this form (which at this moment installs 1.54 version):

`RUN apt-get install -y make cmake libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-python-dev libboost-regex-dev libboost-system-dev libboost-thread-dev`

I have not checked the result, but at least it builds.

**Comment by xingfuryda** [comment]
Thanks, I will give that a try. I had noticed that my openstreetmap-import-docker builds fine with the 1.55 dependancies: https://github.com/xingfuryda/openstreetmap-import-docker/blob/master/Dockerfile

However, openstreemap-import-docker does not use mapnik so this would explain why it builds fine.
